export const dropdownParent = "w-[500px] absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 p-5 rounded-xl shadow-lg shadow-black bg-gray-100"
export const grid = "grid grid-cols-2 gap-5"
export const titleParent = "flex justify-between mb-7 items-center"
export const title = "font-bold text-xl "
export const xIcon = "cursor-pointer duration-300 hover:text-red-500 active:scale-75"
export const resetBtn = "p-3 bg-rose-500 rounded-lg duration-300 active:scale-95 shadow-md text-white font-semibold shadow-gray-400 hover:scale-105"
export const submitBtn = "p-3 bg-green-500 rounded-lg duration-300 active:scale-95 shadow-md text-white font-semibold shadow-gray-400 hover:scale-105"