import type { Metadata } from "next";
import { Poppins,Montserrat } from "next/font/google";
import "./globals.css";
import Sidenav from "@/Components/Sidenav/Sidenav";
import Topnav from "@/Components/TopNav/Topnav";
import BottomNav from "@/Components/BottomNav/BottomNav";
import AppProvider from "@/redux/provider/Provider";

const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <AppProvider>
          <main className="h-screen grid grid-cols-1 md:grid-cols-[260px_1fr]">
            <div className="hidden overflow-y-auto md:block bg-blue-50 h-full">
              <Sidenav />
            </div>
            <div className="flex flex-col overflow-y-auto">
              <div className="h-20 w-full">
                <Topnav />
              </div>
              <div className="flex-1 w-full overflow-y-auto">{children}</div>
            </div>
          </main>
          <BottomNav />
        </AppProvider>
      </body>
    </html>
  );
}
