export const transactions = [
    {
      sender: "James Cameron",
      beneficiaryName: "Larry Johnson Page",
      beneficiaryAccountNumber: "2121212345",
      beneficiaryBankName: "Chase Bank",
      beneficiaryBalance: 200125,
      amountTransferred: "$4,000.00",
      transferType: "Domestic Transfer",
      date: "20-04-24",
      transactionStatus: "Successful",
    },
    {
      sender: "Sarah Connor",
      beneficiaryName: "John Doe",
      beneficiaryAccountNumber: "3456781234",
      beneficiaryBankName: "Bank of America",
      beneficiaryBalance: 50000,
      amountTransferred: "$1,500.00",
      transferType: "International Transfer",
      date: "21-05-10",
      transactionStatus: "Pending",
    },
    {
      sender: "Michael Scott",
      beneficiaryName: "Dwight Schrute",
      beneficiaryAccountNumber: "9876543210",
      beneficiaryBankName: "Wells Fargo",
      beneficiaryBalance: 75000,
      amountTransferred: "$2,000.00",
      transferType: "Domestic Transfer",
      date: "22-06-15",
      transactionStatus: "Successful",
    },
    {
      sender: "Tony Stark",
      beneficiaryName: "Pepper Potts",
      beneficiaryAccountNumber: "1234432112",
      beneficiaryBankName: "Citibank",
      beneficiaryBalance: 1000000,
      amountTransferred: "$10,000.00",
      transferType: "Domestic Transfer",
      date: "23-07-12",
      transactionStatus: "Failed",
    },
    {
      sender: "Bruce Wayne",
      beneficiaryName: "Alfred Pennyworth",
      beneficiaryAccountNumber: "1122334455",
      beneficiaryBankName: "Gotham National Bank",
      beneficiaryBalance: 300000,
      amountTransferred: "$7,500.00",
      transferType: "Domestic Transfer",
      date: "24-08-05",
      transactionStatus: "Successful",
    },
    {
      sender: "Clark Kent",
      beneficiaryName: "Lois Lane",
      beneficiaryAccountNumber: "5566778899",
      beneficiaryBankName: "Metropolis Federal Bank",
      beneficiaryBalance: 100000,
      amountTransferred: "$5,000.00",
      transferType: "International Transfer",
      date: "24-09-01",
      transactionStatus: "Pending",
    },
    {
      sender: "Peter Parker",
      beneficiaryName: "Aunt May",
      beneficiaryAccountNumber: "9988776655",
      beneficiaryBankName: "Queens Community Bank",
      beneficiaryBalance: 20000,
      amountTransferred: "$500.00",
      transferType: "Domestic Transfer",
      date: "23-03-18",
      transactionStatus: "Successful",
    },
    {
      sender: "Diana Prince",
      beneficiaryName: "Steve Trevor",
      beneficiaryAccountNumber: "6677889900",
      beneficiaryBankName: "Amazonian Trust Bank",
      beneficiaryBalance: 250000,
      amountTransferred: "$8,000.00",
      transferType: "Domestic Transfer",
      date: "24-02-22",
      transactionStatus: "Failed",
    },
    {
      sender: "Natasha Romanoff",
      beneficiaryName: "Nick Fury",
      beneficiaryAccountNumber: "1234567890",
      beneficiaryBankName: "Shield Bank",
      beneficiaryBalance: 400000,
      amountTransferred: "$6,500.00",
      transferType: "International Transfer",
      date: "25-05-14",
      transactionStatus: "Successful",
    },
    {
      sender: "Steve Rogers",
      beneficiaryName: "Bucky Barnes",
      beneficiaryAccountNumber: "4321123444",
      beneficiaryBankName: "Captain's Bank",
      beneficiaryBalance: 600000,
      amountTransferred: "$12,000.00",
      transferType: "Domestic Transfer",
      date: "24-10-30",
      transactionStatus: "Pending",
    }
  ];
  

  export const Blur = "backdrop-blur-xl"
  export const Black = "bg-black/70"
  export const White= "bg-white/70"